#!/usr/bin/env node

/**
 * Auto-merge script for version sync PRs
 * Handles the logic for automatically merging PRs created by version sync workflows
 */

const { execSync } = require('child_process');
const { readFileSync } = require('fs');

// Helper function to execute shell commands
function exec(command) {
  try {
    return execSync(command, { encoding: 'utf8', stdio: 'pipe' }).trim();
  } catch (error) {
    console.error(`Command failed: ${command}`);
    console.error(error.message);
    throw error;
  }
}

// Get environment variables
const { GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_EVENT_NAME, GITHUB_EVENT_PATH } = process.env;

// Validate required environment variables
if (!GITHUB_TOKEN || !GITHUB_REPOSITORY) {
  console.error('❌ Missing required environment variables: GITHUB_TOKEN, GITHUB_REPOSITORY');
  process.exit(1);
}

async function main() {
  console.log('🤖 Auto-merge bot starting...');
  console.log(`Event: ${GITHUB_EVENT_NAME}`);

  // Read event payload
  let eventPayload;
  try {
    eventPayload = JSON.parse(readFileSync(GITHUB_EVENT_PATH, 'utf8'));
  } catch (error) {
    console.error('❌ Failed to read event payload');
    process.exit(1);
  }

  // Extract PR number based on event type
  let prNumber = null;

  if (GITHUB_EVENT_NAME === 'pull_request') {
    prNumber = eventPayload.pull_request?.number;
  } else if (
    GITHUB_EVENT_NAME === 'workflow_run' &&
    eventPayload.workflow_run?.pull_requests?.length > 0
  ) {
    prNumber = eventPayload.workflow_run.pull_requests[0].number;
  } else if (
    GITHUB_EVENT_NAME === 'check_suite' &&
    eventPayload.check_suite?.pull_requests?.length > 0
  ) {
    prNumber = eventPayload.check_suite.pull_requests[0].number;
  }

  if (!prNumber) {
    console.log('ℹ️ No PR found for this event - exiting');
    return;
  }

  console.log(`🔍 Checking PR #${prNumber}`);

  // Use GitHub CLI to get PR details
  let prData;
  try {
    const prJson = exec(`gh pr view ${prNumber} --json title,author,headRefName,state,mergeable`);
    prData = JSON.parse(prJson);
  } catch (error) {
    console.error(`❌ Failed to get PR details for #${prNumber}`);
    process.exit(1);
  }

  console.log(`📋 PR Details:`);
  console.log(`   Title: ${prData.title}`);
  console.log(`   Author: ${prData.author.login}`);
  console.log(`   Branch: ${prData.headRefName}`);
  console.log(`   State: ${prData.state}`);

  // Check if this is a version sync PR that should be auto-merged
  const isVersionSyncPR =
    /^chore: sync package\.json version to \d+\.\d+\.\d+$/.test(prData.title) &&
    prData.headRefName.startsWith('sync-version/') &&
    prData.author.login === 'github-actions[bot]' &&
    prData.state === 'OPEN';

  if (!isVersionSyncPR) {
    console.log('❌ Not a version sync PR - skipping auto-merge');
    return;
  }

  console.log('✅ This is a version sync PR - checking if ready to merge');

  // Check if PR is mergeable
  if (prData.mergeable !== 'MERGEABLE') {
    console.log(`⚠️ PR is not mergeable (status: ${prData.mergeable}) - skipping`);
    return;
  }

  // Check if all checks have passed
  try {
    const checksJson = exec(`gh pr checks ${prNumber} --json state,conclusion`);
    const checks = JSON.parse(checksJson);

    const hasFailedChecks = checks.some(
      (check) => check.state === 'COMPLETED' && check.conclusion !== 'SUCCESS',
    );

    const hasPendingChecks = checks.some(
      (check) => check.state === 'IN_PROGRESS' || check.state === 'QUEUED',
    );

    if (hasFailedChecks) {
      console.log('❌ Some checks failed - will not auto-merge');

      // Add comment about failed checks
      exec(`gh pr comment ${prNumber} --body "❌ **Auto-merge blocked**

This version sync PR has failing checks and will not be automatically merged.

Please review the failed checks and address any issues, or merge manually if the failures are acceptable.

*This message was generated by the Auto-Merge Bot.*"`);
      return;
    }

    if (hasPendingChecks) {
      console.log('⏳ Some checks are still pending - waiting');
      return;
    }

    console.log('🎯 All checks passed - attempting to merge');

    // Attempt to merge the PR with squash (enforcing single commit per merge)
    exec(`gh pr merge ${prNumber} --squash --auto --delete-branch`);

    console.log(`✅ Successfully enabled auto-merge for PR #${prNumber}`);

    // Add success comment
    exec(`gh pr comment ${prNumber} --body "🎉 **Auto-merge enabled!**

This version sync PR will be automatically merged once all checks pass.

**Summary:**
- ✅ All validation checks are passing
- ✅ Auto-merge enabled with squash and merge
- 🏷️ Version sync will complete automatically

*This action was performed by the Auto-Merge Bot.*"`);
  } catch (error) {
    console.error('❌ Failed to merge PR:', error.message);

    // Add error comment
    exec(`gh pr comment ${prNumber} --body "⚠️ **Auto-merge failed**

All checks passed but the automatic merge failed. This may be due to:
- Merge conflicts
- Branch protection rules
- Insufficient permissions

Please merge manually.

Error: \`${error.message}\`

*This message was generated by the Auto-Merge Bot.*"`);
  }
}

main().catch((error) => {
  console.error('❌ Auto-merge bot failed:', error);
  process.exit(1);
});
